<?php $this->headLink()
        ->appendStylesheet("http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css")
        ->appendStylesheet("http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/base/jquery-ui.css")
        ->appendStylesheet($this->basePath() . '/css/jquery.dataTables.yadcf.css')
        ->appendStylesheet($this->basePath() . '/css/survey/manageVideos.css')
?>
<?php $this->headScript()
        ->appendFile("http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" ,   'text/javascript')
        ->appendFile("http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" ,   'text/javascript')
        ->appendFile("http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js" ,   'text/javascript')
        ->appendFile($this->basePath() . '/js/jquery.dataTables.yadcf.js',   'text/javascript')
        ->appendFile($this->basePath() . '/js/survey/manageVideos.js',    'text/javascript')
?>
<?php 
    $surveyId = $this->layout()->surveyId;
    $videosUnderSurvey = $this->layout()->videosUnderSurvey;
    $removedVideosUnderSurvey = $this->layout()->removedVideosUnderSurvey;
?>
<h2>Current Videos</h2>
<a href="<?php echo $this->url('survey',
            			array('controller'=>'survey','action'=>'edit','id'=>$surveyId));?>">Back</a>
<form id="meridSurveyVideos" type="POST">    
    <table cellpadding="0" cellspacing="0" border="0" id="surveyVideos">
        <thead>
            <tr>
            <th>Remove</th>
            <th>Edit</th>
            <th>Name</th>
            <th>Link</th>
            <th>Offset Time</th>
            <th>Position</th>
            </tr>
        </thead>
        <tbody>
                <?php 
                    foreach($videosUnderSurvey as $video)
                    {
                    ?>
                    <tr id="<?php echo $video->id;?>">
                    <td class="changers"><a href="#" id="<?php echo $video->id; ?>" class="remove">Remove</a></td>
                    <td class="changers"><a href="#" id="<?php echo $video->id; ?>" class="editpts">Edit</a></td>
                    <td id="<?php echo $video->id; ?>" class="name"><?php echo $video->name; ?></td>
                    <td id="<?php echo $video->id; ?>" class="link"><?php echo $video->link; ?></td>
                    <td id="<?php echo $video->id; ?>" class="offsetTime"><?php echo $video->offsetTime; ?></td>
                    <td id="<?php echo $video->id; ?>" class="position"><?php echo $video->position; ?></td>
                    </tr>
                <?php
                    }
                    ?>
        </tbody>
    </table><br/>
    <input name="id" class="hidden" type="hidden" value=""/>
    <div id="confirmRemove"></div> 
</form> 
<br/>

<h2>Removed Videos</h2>

<form id="meridRemovedVideos" type="POST">    
    <table cellpadding="0" cellspacing="0" border="0" id="removedVideos">
        <thead>
            <tr>
            <th>Reinstate</th>
            <th>Name</th>
            <th>Link</th>
            <th>Offset Time</th>
            <th>Position</th>
            </tr>
        </thead>
        <tbody>
                <?php 
                    foreach($removedVideosUnderSurvey as $removedVideo)
                    {
                    ?>
                <tr id="<?php echo $removedVideo->id; ?>">
                    <td class="changers"><a href="#" id="<?php echo $removedVideo->id; ?>" class="reinstate">Reinstate</a></td>
                    <td id="<?php echo $removedVideo->id; ?>" class="name"><?php echo $removedVideo->name; ?></td>
                    <td id="<?php echo $removedVideo->id; ?>" class="link"><?php echo $removedVideo->link; ?></td>
                    <td id="<?php echo $removedVideo->id; ?>" class="offsetTime"><?php echo $removedVideo->offsetTime; ?></td>
                    <td id="<?php echo $removedVideo->id; ?>" class="position"><?php echo $removedVideo->position; ?></td>
                </tr>
                <?php
                    }
                    ?>
        </tbody>
    </table><br/>
    <input name="id" class="hidden" type="hidden" value=""/>
    <div id="confirmReinstate"></div> 
</form><br/> 
