<html>
	<head>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript" charset="utf-8">
		</script>
	<link rel="stylesheet" type="text/css" href="group.css"/>
	</head>

<body>
	<h1> Create User Group </h1>

<ul id="sidemenu">
<li><a href="#">Home</a></li>
<li><a href="#">Project 1</a></li>
<li><a href="#">Project 2</a></li>
<li><a href="#">Project 3</a></li>
</ul>

	<form id="createusergroup" method="post">
		Group Name: <input type="text" name="gname" id="gname"/> <br/>
		Description: <br/><textarea id="desc" rows="5" cols="70"></textarea>

		<h3>Group Members: </h3>

		<table border="1">
			<tr>
				<th>In Group?</th>
				<th>Instrument</th>
				<th>Player Number</th>
				<th>Desk</th>
				<th>Playing Musical Part</th>
				<th>Email Address</th>
				<th>Username</th>
				<th>Has Account</th>
				<th>Consented to project</th>	
			</tr>	
			<tr>
				<td><input id="checkg1" name="checkg1" type="checkbox"/></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><input id="checkg2" name="checkg2" type="checkbox"/></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><input id="checkg3" name="checkg3" type="checkbox"/></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td><input id="checkg4" name="checkg4" type="checkbox"/></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
		<table>
	<br/>
	<input type="submit" id="creategroup" value="Create Group"/>
</form>
</body>

</html>