<div>
    <form method="post" action ="/projectMember/addHandler">
        <label for="email">email</label>
        <input name="email" type="text" value="tesasdft@cornell.edu"/>
        <label for="project">project</label>
        <input name="project" type="text" value="532bc8cdea441c7c06000000"/> <!-- in real form, this should be hidden input -->
        <label for="username">username</label>
        <input name="username" type="text"/>
        <label for="instrument">instrument</label>
        <input name="instrument" type="text"/>
        <label for="playerNumber">playerNumber</label>
        <input name="playerNumber" type="text"/>    
        <label for="desk">desk</label>
        <input name="desk" type="text"/>
        <label for="playingPart">playingPart</label>
        <input name="playingPart" type="text"/>
        <label for="principal">principal</label>
        <input name="principal" type="text"/>

        <input type="submit" value="submit"/>
    </form>
</div>
</br>
<div>
    <form method="post" action ="/projectMember/editHandler">
        <label for="participant">participant</label>
        <input name="participant" type="text"/>
        <label for="user" >user</label>
        <input name="user" type="text" value="532b9ee5ea441c8a7d000000"/>
        <label for="project">project</label>
        <input name="project" type="text" value="532bc8cdea441c7c06000000"/>
        <label for="username">username</label>
        <input name="username" type="text"/>
        <label for="instrument">instrument</label>
        <input name="instrument" type="text"/>
        <label for="playerNumber">playerNumber</label>
        <input name="playerNumber" type="text"/>    
        <label for="desk">desk</label>
        <input name="desk" type="text"/>
        <label for="playingPart">playingPart</label>
        <input name="playingPart" type="text"/>
        <label for="principal">principal</label>
        <input name="principal" type="text"/>

        <input type="submit" value="submit"/>
    </form>
</div>
</br>
<div>
    <form method="post" action ="/projectMember/deleteHandler">
        <label for="participant">participant</label>
        <input name="participant" type="text"/>
        <input type="submit" value="submit"/>
    </form>
</div>
</br>
<div id="projects">
    
</div>
