<?php $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/user/register.css')
?>
<?php $this->headScript()
        ->appendFile($this->basePath() . '/js/jquery.js')
        ->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js' , 'text/javascript')
        ->appendFile($this->basePath() . '/js/jquery.validate.js')
        ->appendFile($this->basePath() . '/js/user/register.js')
        ->appendFile($this->basePath() . '/js/navigate.js')
?>

<h1>Sign Up (Researcher Only)</h1>
<form id="signUp" name="signUp" method="POST" action="<?php echo $this->url('user', array('controller' => 'user', 'action' => 'registerHandler'));
?>">
    <h4>MERID Account Info:</h4>
    <fieldset>
        Full Name: <input id="name" name="name" type="text"/><br/>
        Display Name: <input id="username" name="username" type="text"/> <br/>
        
        <h4>Contact Info:</h4>
        Email: <input id="email" name="email" type="email"/><div id="error"></div><div id="valid"></div>
        Mailing Address: <br/>
        <textarea name="mailAdd" rows="10" cols="60">
        </textarea> <br/>
        Phone Number:<br/>
        <textarea id="phoneNumber" name="phoneNumber" rows="2" cols="50">
        </textarea><br/>

        <h4>Research Background:</h4>
        Research Organization: <input id="org" name="org" type="text"/><br/>
        Work of Study: <input id="wos" name="wos" type="text"/><br/>
        Biography:<br/>
        <textarea rows="7" name="bio" cols="60" onfocus="if(this.value == 'A brief background of yourself, your studies, and your current pursuits') 
            { this.value = ''; }" onblur="if (this.value == '') { this.value='A brief background of yourself, your studies, and your current pursuits'; }" >A brief background of yourself, your studies, and your current pursuits</textarea>
        <br/>
        <a href="#">Terms of Use</a><br/><br/>
        I have read and agreed to the terms of use <input id="tos" name="tos" type="checkbox"/><br/><br/>

        <input id="signup" type="submit" value="Sign Up"/>
    </fieldset>
</form>
