<html>
	<head>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript" charset="utf-8">
		</script>
		<link rel="stylesheet" href="account.css" type="text/css"/>
	</head>	
<body>
<h1>Sign Up (Researcher Only)</h1>

<h4>MERID Account Info:</h4>
Full Name: <input id="fname" type="text"/>
Username: <input id="uname" type="text"/> <br/>
Password: <input id="pass" type="text"/>
Confirm Password: <input id="confpass" type="text"/> <br/>

<h4>Contact Info:</h4>
Email: <input id="email" type="text"/>
Mailing Address: <br/>
<textarea rows="10" cols="60">
</textarea> <br/>
Phone #: <input id="phone" type="text"/><br/>

<h4>Research Background:</h4>
Research Organization: <input id="org" type="text"/><br/>
Work of Study: <input id="wos" type="text"/><br/>
Biography:<br/>
<textarea rows="10" cols="60">
A brief background of yourself, your studies, and your current pursuits			
</textarea>

<br/>
<a href="#">Terms of Use</a><br/>
<input id="tos" type="checkbox"/> I have read and agreed to the terms of use <br/>

<input id="cancel" type="button" value="Cancel"/>
<input id="signup" type="button" value="Sign Up"/>

</body>
</html>           
