<html>
  <head>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript" charset="utf-8">
	</script>
	<link rel="stylesheet" type="text/css" href="user.css"/>
 
  </head>

<body>
	<h1> Project 1: Participant Information</h1>

	<ul id="sidemenu">
		<li><a href="#">Home</a></li>
		<li><a href="#">Project 1</a></li>
		<li><a href="#">Project 2</a></li>
		<li><a href="#">Project 3</a></li>
	</ul>

	<h4>Account Info: </h4>
			<table border="1">
			<tr>
				<th>Score</th>
				<th>Name</th>
				<th>Username</th>
				<th>Account Confirmed</th>
				<th>Invitation Status</th>	
			</tr>	
			<tr>
				<td>1000</td>
				<td>User 1</td>
				<td>uname1</td>
				<td>Yes</td>
				<td>Accepted</td>
			</tr>
			<tr>
				<td>1001</td>
				<td>User 2</td>
				<td>uname2</td>
				<td>Yes</td>
				<td>Not yet accepted</td>
			</tr>
			<tr>
				<td>1002</td>
				<td>User 3</td>
				<td>uname3</td>
				<td>No</td>
				<td>Not yet accepted</td>
			</tr>
			<tr>
				<td>1003</td>
				<td>User 4</td>
				<td>uname4</td>
				<td>Yes</td>
				<td>Rejected</td>
			</tr>
			<tr>
				<td>1004</td>
				<td>User 5</td>
				<td>uname5</td>
				<td>No</td>
				<td>Not yet accepted</td>
			</tr>
		<table>

<h4>Additional Info: </h4>
			<table border="1">
			<tr>
				<th>Instrument</th>
				<th>Section Player #</th>
				<th>Desk #</th>
				<th>Part played</th>
			</tr>	
			<tr>
				<td>Violin</td>
				<td>1</td>
				<td>11</td>
				<td>Part 111</td>
			</tr>
			<tr>
				<td>Cello</td>
				<td>2</td>
				<td>22</td>
				<td>Part 222</td>
			</tr>
			<tr>
				<td>Flute</td>
				<td>3</td>
				<td>33</td>
				<td>Part 333</td>
			</tr>
			<tr>
				<td>Viola</td>
				<td>4</td>
				<td>44</td>
				<td>Part 444</td>
			</tr>
			<tr>
				<td>Bass</td>
				<td>5</td>
				<td>55</td>
				<td>Part 555</td>
			</tr>
		<table>
		<br/>
		<input id="invcre" type="button" value="Invite/Create new participant account"/>	
</body>
</html>