<h1>View User</h1>

<div style="float:left;margin-right:20px;height:200px;width:200px;border:2px solid;">
    Picture?
</div>

<div style="font-size:20px;">
    <table>
        <tr>
            <td>Name:</td>
            <td></td>
        </tr>
        <tr>
            <td>Email:</td>
            <td></td>
        </tr>
        <tr>
            <td>Orchestra:</td>
            <td></td>
        </tr>
        <tr>
            <td>Instrument(s):</td>
            <td></td>
        </tr>
        <tr>
            <td>Part #:</td>
            <td></td>
        </tr>
        <tr>
            <td>Position:</td>
            <td></td>
        </tr>
    </table>
</div>