<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
				->prependStylesheet($this->basePath() . '/css/index/contactUs.css')
?>
<h1>Contact Us</h1>
<div id="content">
<img id="baileypic" src="<?php echo $this->basePath('img/bailey.jpg'); ?>" alt="nobailey"/><br/>
<p id="baileyInfo">    
<span id="name">Dr. Graeme Orman Bailey </span><br/><br/>
<span class="info">Campus Address:</span><br/> 
                4107B Upson Hall <br/>
                Cornell University <br/>
                Ithaca, NY 14853 <br/><br/>

<span class="info">Phone Numbers:</span><br/>
               607-255-9210 <br/>
               607-255-0980 <br/><br/>
               
<span class="info">Email Address:</span><br/> 
               gob1@cornell.edu <br/>
               bailey@cs.cornell.edu <br/>
               bailey@math.cornell.edu <br/>
    
</p>    
</div>
