<div id="aboutWrapper">
<h2>About MERID</h2>
<p>Media Enabled Research Interface and Database<br />
<a href="<?php echo $this->url('index',
            array('controller'=>'index','action'=>'about'));?>">More about MERID</a>
</p>
</div>

<div id="logInWrapper">
<h2>Log In</h2>
<form method="post" action="<?php echo $this->url('user',
            array('controller'=>'index','action'=>'login'));?>">
	<p>User Email: <input type="text" name= "identity"/></p>
	<p>Password: <input type="password" name= "credential"/></p>
	<input type="submit" value="Log In" />
</form>
</div>
<div class="addedLinks">
Interested in doing research? Request a <a href="<?php echo $this->url('user',
            array('controller'=>'user','action'=>'register'));?>">researcher's account</a>
</div>			
			
<!--<html>
	<head>
		<title>Sign Up</title>
		<link rel="stylesheet" type="text/css" href="css/reset.css" />
		<link rel="stylesheet" type="text/css" href="css/main.css" />
		<link rel="stylesheet" type="text/css" href="css/signUp.css" />

		<div id="header">
			<div id="MERID">
				<b>M</b>edia <b>E</b>nabled <b>R</b>espondent <b>I</b>nterface and <b>D</b>atabase<br/> (<b>MERID</b>)
			</div>
		</div>
	</head>

	<body>
		<div id="body">
			<div id ="sign_up" class="formDiv">
				<form action="profilePage.html">
					<p id="signup_name">Name</p>
					<input id="signup_enter_name" type="text" />
					<p id="email_address">Email address</p>
					<input id="signup_enter_email_address" type="text"><br/><br/><br/></input>
					<input type="submit" class="signup_buttons" value="Sign Up" />
				</form>
			</div>

			<div id="log_in" class="formDiv">
				<form action="profilePage.html">
					<p id="login_username">Username</p>
					<input id="login_enter_username" type="text" />
					<p id="login_password">Password</p>
					<input id="login_enter_password" type="text"><br/><br/><br/></input>
					<input type="submit" class="signup_buttons" value="Log In" />
				</form>
			</div>
		</div>
	</body>
	<footer>
		<div id="footer">
			<div id="about">ABOUT</div>
			<div id="contact_us">CONTACT US</div>
			<div id="help">HELP</div>
		</div>
	</footer>
</html>
-->
